"""
main.py - All API routes for MyCharacterAI.

Run locally:
    uvicorn main:app --reload

Interactive API docs (auto-generated by FastAPI) will be at:
    http://localhost:8000/docs
"""
import os

import jwt
from dotenv import load_dotenv
from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from sqlalchemy.orm import Session

from database import get_db, init_db, User, Character, Chat, Message
from auth import get_password_hash, verify_password, create_access_token, decode_access_token
from ai_service import get_ai_provider
from schemas import (
    SignupRequest, LoginRequest, TokenResponse, UserOut,
    CharacterCreate, CharacterOut, ChatMessageRequest, ChatReplyResponse,
    MessageOut, ChatOut,
)
from seed_data import DEFAULT_CHARACTERS

load_dotenv()

app = FastAPI(title="MyCharacterAI API")
from fastapi.middleware.cors import CORSMiddleware
app.add_middleware(
       CORSMiddleware,
       allow_origins=["*"], # we will lock this later. * works for first deploy
       allow_credentials=True,
       allow_methods=["*"],
       allow_headers=["*"],
   )

# Allow the static frontend (served from a different port/file://) to call this API.
# Lock this down to your real domain before deploying publicly.
app.add_middleware(
    CORSMiddleware,
    allow_origins=os.getenv("CORS_ORIGINS", "*").split(","),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

bearer_scheme = HTTPBearer()

MAX_HISTORY_MESSAGES = 10  # how many past messages we feed back to the AI for memory


@app.on_event("startup")
def on_startup():
    init_db()
    _seed_characters_if_empty()


def _seed_characters_if_empty():
    """Inserts any DEFAULT_CHARACTERS not already present (matched by name).
    Safe to run on every startup - won't duplicate characters that already
    exist, and will pick up new ones added to seed_data.py automatically."""
    db = next(get_db())
    try:
        existing_names = {name for (name,) in db.query(Character.name).all()}
        for c in DEFAULT_CHARACTERS:
            if c["name"] not in existing_names:
                db.add(Character(**c, created_by=None, is_public=True))
        db.commit()
    finally:
        db.close()


# ---------- Auth dependency ----------

def get_current_user(
    credentials: HTTPAuthorizationCredentials = Depends(bearer_scheme),
    db: Session = Depends(get_db),
) -> User:
    token = credentials.credentials
    try:
        payload = decode_access_token(token)
        user_id = payload.get("sub")
        if user_id is None:
            raise ValueError("missing sub")
    except (jwt.PyJWTError, ValueError):
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Invalid or expired token")

    user = db.query(User).filter(User.id == int(user_id)).first()
    if user is None:
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "User not found")
    return user


# ---------- Auth routes ----------

@app.post("/api/signup", response_model=TokenResponse)
def signup(payload: SignupRequest, db: Session = Depends(get_db)):
    if db.query(User).filter(User.email == payload.email).first():
        raise HTTPException(status.HTTP_400_BAD_REQUEST, "Email already registered")

    user = User(email=payload.email, password_hash=get_password_hash(payload.password))
    db.add(user)
    db.commit()
    db.refresh(user)

    token = create_access_token({"sub": str(user.id)})
    return TokenResponse(access_token=token)


@app.post("/api/login", response_model=TokenResponse)
def login(payload: LoginRequest, db: Session = Depends(get_db)):
    user = db.query(User).filter(User.email == payload.email).first()
    if not user or not verify_password(payload.password, user.password_hash):
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Incorrect email or password")

    token = create_access_token({"sub": str(user.id)})
    return TokenResponse(access_token=token)


@app.get("/api/me", response_model=UserOut)
def me(user: User = Depends(get_current_user)):
    return user


# ---------- Character routes ----------

@app.get("/api/characters", response_model=list[CharacterOut])
def list_characters(db: Session = Depends(get_db)):
    return db.query(Character).filter(Character.is_public == True).all()  # noqa: E712


@app.get("/api/characters/{character_id}", response_model=CharacterOut)
def get_character(character_id: int, db: Session = Depends(get_db)):
    char = db.query(Character).filter(Character.id == character_id).first()
    if not char:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Character not found")
    return char


@app.post("/api/characters", response_model=CharacterOut)
def create_character(
    payload: CharacterCreate,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    char = Character(
        name=payload.name,
        description=payload.description,
        personality=payload.personality,
        avatar_url=payload.avatar_url,
        is_public=payload.is_public,
        created_by=user.id,
    )
    db.add(char)
    db.commit()
    db.refresh(char)
    return char


# ---------- Chat routes ----------

@app.get("/api/chats", response_model=list[ChatOut])
def list_my_chats(user: User = Depends(get_current_user), db: Session = Depends(get_db)):
    return (
        db.query(Chat)
        .filter(Chat.user_id == user.id)
        .order_by(Chat.updated_at.desc())
        .all()
    )


@app.get("/api/chats/{character_id}/messages", response_model=list[MessageOut])
def get_chat_history(
    character_id: int,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Returns full message history for this user+character (empty list if no chat yet)."""
    chat = (
        db.query(Chat)
        .filter(Chat.user_id == user.id, Chat.character_id == character_id)
        .first()
    )
    if not chat:
        return []
    return chat.messages


@app.post("/api/chat", response_model=ChatReplyResponse)
def send_chat_message(
    payload: ChatMessageRequest,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    character = db.query(Character).filter(Character.id == payload.character_id).first()
    if not character:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "Character not found")

    # 1. Find or create the chat session for this user+character pair
    chat = (
        db.query(Chat)
        .filter(Chat.user_id == user.id, Chat.character_id == character.id)
        .first()
    )
    if not chat:
        chat = Chat(user_id=user.id, character_id=character.id, title=payload.message[:50])
        db.add(chat)
        db.commit()
        db.refresh(chat)

    # 2. Save the user's message
    db.add(Message(chat_id=chat.id, role="user", content=payload.message))
    db.commit()

    # 3. Pull recent history (for the AI's short-term memory)
    recent = (
        db.query(Message)
        .filter(Message.chat_id == chat.id)
        .order_by(Message.id.desc())
        .limit(MAX_HISTORY_MESSAGES)
        .all()
    )
    recent.reverse()
    history = [{"role": m.role, "content": m.content} for m in recent if m.role in ("user", "assistant")]
    # Don't double-send the message we just saved - the provider takes it separately.
    history = history[:-1] if history and history[-1]["content"] == payload.message else history

    # 4. Call the AI
    try:
        provider = get_ai_provider()
        reply_text = provider.generate_reply(character.personality, history, payload.message)
    except Exception as e:
        raise HTTPException(status.HTTP_502_BAD_GATEWAY, f"AI provider error: {e}")

    # 5. Save the AI's reply
    ai_message = Message(chat_id=chat.id, role="assistant", content=reply_text)
    db.add(ai_message)
    chat.title = chat.title or payload.message[:50]
    db.commit()

    return ChatReplyResponse(chat_id=chat.id, reply=reply_text)


@app.get("/api/health")
def health():
    return {"status": "ok"}
